services:
  uas:
    image: ghcr.io/utat-uas/dev_env:latest
    hostname: ros-dev
    extra_hosts:
      - "localhost localhost.localdomain ros-dev:127.0.0.1"
    container_name: uas-dev-container
    stdin_open: true
    tty: true
    ipc: host
    init: true
    privileged: true
    environment:
      DISPLAY: $DISPLAY
      XAUTHORITY: /home/${USER}/.Xauthority
      QT_X11_NO_MITSHM: 1
      QT_GRAPHICSSYSTEM: native
    volumes:
      - ../:/home/uas/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
      # - /dev/input:/dev/input
      # - /dev:/dev
    command: /bin/bash
    # network_mode: host
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: cdi
    #           capabilities: [gpu]
    #           device_ids:
    #             - nvidia.com/gpu=all
